#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_PARKING_SPOTS 100
#define MAX_QUEUE_SIZE 50
#define MAX_CLIENTS 10 
#define DEFAULT_PORT 8080
#define MAX_MESSAGE_SIZE 2048
#define SERVER_TICK_SECONDS 1 
#define DEFAULT_SIM_DURATION 300
#define MIN_ARRIVAL_INTERVAL 1 
#define MAX_ARRIVAL_INTERVAL 10 
#define MIN_PARK_DURATION 10 
#define MAX_PARK_DURATION 120
#define MAX_VEHICLE_ID 100000

#define ILOVENIKITA 10

#endif 
